spring:
  profiles:
    active: local
  jpa:
    show-sql: true
    thymeleaf:
      cache: false

server:
  port: 6565

# local 환경
---
spring:
  config:
    activate:
      on-profile: local
  h2:
    console:
      enabled: true
  datasource:
    platform: h2
    url: jdbc:h2:mem:testdb
    data: classpath:data.sql # 시작할 때 실행시킬 script
  jpa:
    hibernate:
      ddl-auto: create-drop

# tb 환경
---
spring:
  config:
    activate:
      on-profile: testbed
  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://arjuna.db.elephantsql.com:5432/fgugucui
    username: fgugucui
    password: x7ic23ri9XSlm3gS86sXiATL88XP0Y0f
    hikari:
      maximum-pool-size: 2
  jpa:
    database: POSTGRESQL
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: create-drop